# References:
# https://github.com/thomasread99/expo-workflows/

name: Build Android

on:
  workflow_dispatch:
    inputs:
      ref:
        type: string
        required: true

jobs:
  build:
    runs-on: ubuntu-latest
    steps:

      - name: Setup repo
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.USTHING_GITHUB_TOKEN }}
          ref: ${{ inputs.ref }}
          repository: USThing/USThingApp

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: latest

      - name: Setup Corepack
        run: |
          corepack enable
          corepack install

      - name: Setup Yarn Cache
        uses: actions/setup-node@v4
        with:
          cache: yarn

      - name: Setup JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: 17
          distribution: microsoft

      - name: Setup Android SDK
        uses: android-actions/setup-android@v3

      - name: Setup Expo and EAS
        uses: expo/expo-github-action@v8
        with:
          token: ${{ secrets.EXPO_TOKEN }}
          expo-version: latest
          eas-version: latest

      - name: Install Dependencies
        run: yarn

      - name: Build
        run: eas build --profile production --platform android --local --non-interactive --output=${{ github.workspace }}/usthing-preview.aab

      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: preview
          path: ${{ github.workspace }}/usthing-preview.apk

      # https://docs.expo.dev/submit/ios/#submitting-your-app-using-ci
      - name: Submit to TestFlight
        run: eas submit --profile production --platform android --non-interactive --path ${{ github.workspace }}/usthing-preview.aab
